### ISSUE TITLE
Data Request

### ISSUE THREAD

**Issue by xxxmmmbbb** [congyingxia/Multi-Grained-NER#2]
There is no data folder in the project. Can you provide data? I want to do your experiment. Thank you very much.

**Comment by czhang99** [comment]
The dataset content is subject to copyright issues. Some useful pointers: 
(ACE 2004) https://catalog.ldc.upenn.edu/LDC2005T09
(ACE 2005) https://catalog.ldc.upenn.edu/LDC2006T06
(CoNLL 2003) https://cogcomp.seas.upenn.edu/page/resource_view/81

**Comment by xxxmmmbbb** [comment]
> The dataset content is subject to copyright issues. Some useful pointers:
> (ACE 2004) https://catalog.ldc.upenn.edu/LDC2005T09
> (ACE 2005) https://catalog.ldc.upenn.edu/LDC2006T06
> (CoNLL 2003) https://cogcomp.seas.upenn.edu/page/resource_view/81

Thank you very much！

**Comment by xxxmmmbbb** [comment]
OSError: Unable to open file (unable to open file: name = '../data/conll2003/elmo/elmo_dev.hdf5', 
How to get Elmo? Dev.hdf5? Let the dataset pass the Elmo training?

**Comment by congyingxia** [comment]
These .hdf5 files come from the Elmo model.  I've updated the data preprocessing part.
 You can follow the "Elmo embeddings part" in "step 0.0 prepare data"  to get these files:

cd data/ace2004/elmo
sh run.sh
