### ISSUE TITLE
Original data format

### ISSUE THREAD

**Issue by xxxmmmbbb** [congyingxia/Multi-Grained-NER#3]
dataset = 'conll2003'
    filename_dev = data_pre + dataset + "/eng.dev"
Is the eng.dev file entered line by line? In the code, what are anchors, anchor ﹣ labels, class ﹣ IDS, sample ﹣ indexes?

**Comment by congyingxia** [comment]
yes, it's line by line. I added some data examples, so you can checkout. 
Those anchors are used for the entity proposals. anchor_labels are 1 (entity), 0(non-entity) or -1(invalid indexes). class_ids are the entity types. sample_indexes are designed for sample negative entity proposals, but it is actually not used in this paper.

You can check out the detector/model/rpn.py to see how the anchors (entity_proposals) are generated.
